name: CI | Create a Conan package test for LearningHub on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Conan Installation ...
      run: |
        pip install conan==2.11.0
        conan profile detect

    - name: Create a Conan package for LearningHub
      run: |
        conan create . --build=missing -u
